### ISSUE TITLE
Crash when trying to close an archive

### ISSUE THREAD

**Issue by DarkAyron** [ladislav-zezula/StormLib#42]
StormLib crashes when trying to close an archive after adding some files.
Backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
#0  0x00007ffff7b6e423 in AllocateFileEntry (ha=0x602130, szFileName=0x7ffff7bc21c9 "(listfile)", lcLocale=0) at src/SBaseFileTable.cpp:1832
#1  0x00007ffff7b735e2 in SFileAddFile_Init (ha=0x602130, szFileName=0x7ffff7bc21c9 "(listfile)", FileTime=0, dwFileSize=72, lcLocale=0, dwFlags=2164261376, phf=0x7fffffffdeb8) at src/SFileAddFile.cpp:431
#2  0x00007ffff7b7a943 in SListFileSaveToMpq (ha=0x602130) at src/SFileListFile.cpp:464
#3  0x00007ffff7b7bc1c in SFileFlushArchive (hMpq=0x602130) at src/SFileOpenArchive.cpp:567
#4  0x00007ffff7b7bd44 in SFileCloseArchive (hMpq=0x602130) at src/SFileOpenArchive.cpp:628
#5  0x0000000000400f14 in main () at test.cc:150
```
test.cc: http://0wx.cat/53e798b22407d13dcf5ff96bd567dddc/
The image files I used for this test can be arbitrary files.

Issue exists since 68e2c2527db10dcfdd9fdc2219c7fe9784abf738

**Comment by ladislav-zezula** [comment]
Yeah, that happens when I am too busy to run complete test.
Fixed in commit 5747ad4910966b27b4da3f0d0e5f085697e5bf7b
